name: Publish NuGet Package (.NET Framework 4.8)

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  build:
    runs-on: windows-latest  # Required for .NET Framework builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore dependencies
        run: nuget restore PersianMonthView.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build project (Release mode)
        run: msbuild PersianMonthViewControl.csproj /p:Configuration=Release

      - name: Create NuGet package
        run: dotnet pack PersianMonthViewControl.csproj --configuration Release --no-build --output bin/Release

      - name: List files in Release folder (debugging)
        run: ls bin/Release/


      - name: Publish to NuGet
        run: nuget push bin/Release/PersianMonthView.*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
